GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/67de57394c4c70d9f5c59989

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "3 blog",
  "url": "some_url",
  "likes": 150,
  "user": "67de47f65305d9b82dd73ed3"
}

###
DELETE http://localhost:3003/api/blogs/67de540f9679a49c28df9a6e

###
PUT http://localhost:3003/api/blogs/67d244bad6ab7fddc273cace
Content-Type: application/json

{
  "likes": 510
}

###
GET http://localhost:3003/api/users
###
GET http://localhost:3003/api/users/67de47f65305d9b82dd73ed3
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "3dnan",
  "name": "adnan abd",
  "password": "adnan"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "3li",
  "password": "123456789"
}